# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-03 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('idserial', models.CharField(max_length=20)),
                ('cardpwd', models.CharField(max_length=25)),
            ],
        ),
    ]
